# Generated by Django 4.1.4 on 2023-01-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMessages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='comision',
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='cuerpo',
            field=models.CharField(max_length=20),
        ),
    ]
