# Generated by Django 4.1.4 on 2023-01-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAccounts', '0002_perfil_first_name_perfil_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(default='', upload_to='imagenAvatars'),
            preserve_default=False,
        ),
    ]
